baseurl = "/"
languageCode = "en-us"
title = "Curious Incidents & Crazy Ideas"
theme = "hugo-xmag"
googleAnalytics = "UA-178518731-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â†©"
hasCJKLanguage = true
enableEmoji = true
paginate = 9

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
    
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
    
[[menu.main]]
    name = "Contribute"
    url = "/contribute/"
    weight = 3
    
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"
    weight = 4

    
[[menu.main]]
    name = "Feedback"
    url = "/feedback/"
    weight = 5

[[menu.top]]
  name = "Homepage"
  url = "/"
  weight = 10

[[menu.top]]
  name = "About"
  url = "/about/"
  weight = 20
  
[[menu.top]]
  name = "Article"
  url = "/articles/"
  weight = 30

[[menu.top]]
  name = "Submit"
  url = "/submission/"
  weight = 40
  
[[menu.top]]    
    name="Search"
    weight= 50

[[menu.top]]
    parent = "Search"
    name = "1-Categories"
    identifier = "search"
    url = "/categories/"
    weight = 51
    
[[menu.top]]
    parent = "Search"
    name = "2-Tags"
    identifier = "tags"
    url = "/tags/"
    weight = 52

[[menu.top]]
    parent = "Search"
    name = "3-Dates"
    identifier = "dates"
    url = "/dates/"
    weight = 53
    
[params]
    description = "A nerds' journal."
    summary_length = 360
    github_edit = "https://github.com/cisquare/ci2.us/edit/master/content/"
    footer = "&copy; CI&#178; | [Github](https://github.com/cisquare) | [Google](https://www.google.com)"

[params.banner]
  src = "/img/logo.pdf"
  alt = "CI2's logo"

[[params.banner.source]]
  media = "(min-width: 715px)"
  srcset = "/img/logo-title.png"
  
[[params.banner.source]]
  media = "(max-width: 380px)"
  srcset = "/img/logo-sub.pdf"
  

[params.text]
    about_author="Author Bio"
     author_delimiter = " / "
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"
    tags = "Keywords: "
  title_categories = "Columns"
  title_tags = "Keyword List"
    
[params.utter]
    enable = true
    repo = "cisquare/comments"
    issueTerm = "pathname" # choose issue in terms of pathname/url/title
    theme = "github-light"
